version: 0.2
phases:
  build:
    commands:
      - ./gradlew clean buildZip
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version
      - sam package
        --template-file template.yml
        --output-template-file package.yml
        --s3-bucket demo-ci-cd-sam-bucket
artifacts:
  files:
    - package.yml
